/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register-coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerCoach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/attendances/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/attendances/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/attendances/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/attendances/{id}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["weekly"];
        put: operations["replaceWeekly"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/availability/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["blocks"];
        put?: never;
        post: operations["createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/availability/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/billing/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/cycles/{cycleId}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/events/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/events/{id}/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changeCapacity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/events/{id}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/events/{id}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["qr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["payments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlans"];
        put?: never;
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/plans/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["setPlanActive"];
        trace?: never;
    };
    "/api/coach/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["board"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["coachView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/consents/{type}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["coachAccept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/consents/{type}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["coachRevoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueReset"];
        delete: operations["revokeReset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{id}/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{studentId}/attendances/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAttendances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{studentId}/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cycles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{studentId}/cycles/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["activeCycle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{studentId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/students/{studentId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["attendancesOfStudent"];
        put?: never;
        post: operations["book_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accept_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/attendances/confirm-qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmQr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/attendances/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/consents/{type}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/consents/{type}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mySessions"];
        put?: never;
        post: operations["book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptConsentRequest: {
            version: string;
        };
        AcceptRequest: {
            acceptData: boolean;
            acceptWhatsapp: boolean;
            dataVersion?: string;
            password?: string;
            token: string;
            whatsappVersion?: string;
        };
        ActiveRequest: {
            active: boolean;
        };
        AffectedStudent: {
            /** Format: uuid */
            attendanceId: string;
            /** Format: uuid */
            studentId: string;
            studentName?: string | null;
        };
        AgendaView: {
            events: components["schemas"]["EventView"][];
            freeBlocks: components["schemas"]["SlotView"][];
        };
        AttendanceView: {
            canCancel: boolean;
            canMark: boolean;
            cancelReason?: string | null;
            /** Format: int32 */
            capacity: number;
            /** @enum {string|null} */
            confirmationMethod?: "QR" | "LATER" | null;
            /** Format: date-time */
            confirmedAt?: string | null;
            /** Format: uuid */
            cycleId: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            /** Format: int32 */
            occupied: number;
            onlyMarkedByCoach: boolean;
            override: boolean;
            overrideReason?: string | null;
            /** Format: uuid */
            rescheduledFrom?: string | null;
            /** Format: date-time */
            startsAt: string;
            /** @enum {string} */
            status: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH";
            studentConfirmed: boolean;
            /** Format: uuid */
            studentId?: string | null;
            studentName?: string | null;
        };
        AttendeeView: {
            /** Format: uuid */
            attendanceId: string;
            canMark: boolean;
            /** @enum {string|null} */
            confirmationMethod?: "QR" | "LATER" | null;
            /** Format: date-time */
            confirmedAt?: string | null;
            minor: boolean;
            onlyMarkedByCoach: boolean;
            override: boolean;
            overrideReason?: string | null;
            /** @enum {string} */
            status: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH";
            studentConfirmed: boolean;
            /** Format: uuid */
            studentId: string;
            studentName: string;
        };
        AuditEntryView: {
            /** @enum {string} */
            action: "BOOK" | "RESCHEDULE" | "MARK" | "CANCEL" | "CONFIRM" | "TRANSFER";
            /** @enum {string} */
            actorRole: "COACH" | "STUDENT";
            /** Format: uuid */
            actorUserId: string;
            /** @enum {string} */
            method: "COACH" | "STUDENT" | "QR" | "LATER";
            /** @enum {string} */
            newStatus: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH";
            /** Format: date-time */
            occurredAt: string;
            /** @enum {string|null} */
            previousStatus?: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH" | null;
            reason?: string | null;
        };
        AuthResponse: {
            /** Format: uuid */
            coachId: string;
            role: string;
            token: string;
        };
        BlockCreated: {
            affectedEvents: components["schemas"]["EventView"][];
            block: components["schemas"]["BlockSummary"];
        };
        BlockInput: {
            /** Format: date-time */
            endsAt: string;
            reason?: string;
            /** Format: date-time */
            startsAt: string;
        };
        BlockSummary: {
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            id: string;
            reason?: string | null;
            /** Format: date-time */
            startsAt: string;
        };
        BoardCounts: {
            /** Format: int32 */
            active: number;
            /** Format: int32 */
            all: number;
            /** Format: int32 */
            expiring: number;
            /** Format: int32 */
            inactive: number;
        };
        BoardRow: {
            active: boolean;
            activeCycle: boolean;
            /** Format: int32 */
            classesIncluded?: number | null;
            /** Format: int32 */
            classesRemaining?: number | null;
            /** Format: int32 */
            daysUntilEnd?: number | null;
            /** Format: date */
            endDate?: string | null;
            /** @enum {string|null} */
            expiringBy?: "DAYS" | "CLASSES" | "BOTH" | null;
            expiringSoon: boolean;
            fullName: string;
            hasAccount: boolean;
            minor: boolean;
            needsRenewal: boolean;
            /** Format: int32 */
            pendingMarks: number;
            /** @enum {string|null} */
            planModality?: "PERSONALIZED" | "SEMI_PERSONALIZED" | null;
            /** @enum {string} */
            status: "SUSPENDIDO" | "SIN_ACTIVAR" | "SIN_CLASES" | "VENCIDO" | "SIN_PLAN" | "POR_VENCER" | "AL_DIA";
            /** Format: uuid */
            studentId: string;
        };
        BookCommand: {
            /** Format: date-time */
            startsAt: string;
        };
        BrandView: {
            brandName: string;
            primaryColor?: string | null;
        };
        CancelAttendancesCommand: {
            attendanceIds: string[];
            reason: string;
        };
        CancelAttendancesResult: {
            cancelled: components["schemas"]["AttendanceView"][];
        };
        CancelEventCommand: {
            reason: string;
        };
        CancelResult: {
            cancelled: components["schemas"]["AttendanceView"];
            replacement?: components["schemas"]["AttendanceView"] | null;
        };
        ChangeCapacityCommand: {
            /** Format: int32 */
            capacity: number;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword?: string;
        };
        ClassRow: {
            /** Format: uuid */
            attendanceId: string;
            canConfirm: boolean;
            cancelReason?: string | null;
            /** @enum {string|null} */
            confirmationMethod?: "QR" | "LATER" | null;
            date: string;
            /** Format: int32 */
            number?: number | null;
            onlyMarkedByCoach: boolean;
            override: boolean;
            /** Format: date-time */
            startsAt: string;
            /** @enum {string} */
            status: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH";
            studentConfirmed: boolean;
            time: string;
        };
        CoachBookCommand: {
            override?: boolean;
            overrideReason?: string;
            /** Format: date-time */
            startsAt: string;
        };
        CoachCancelCommand: {
            /** Format: date-time */
            newStartsAt?: string;
            override?: boolean;
            overrideReason?: string;
            reason: string;
        };
        CoachSettingsView: {
            /** Format: int32 */
            cancelWindowHours: number;
            /** Format: int32 */
            classDurationMinutes: number;
            /** Format: int32 */
            confirmationWindowHours: number;
            /** Format: int32 */
            defaultGroupCapacity: number;
            /** Format: int32 */
            expiringSoonClasses: number;
            /** Format: int32 */
            expiringSoonDays: number;
            gymConsentConfirmed: boolean;
            /** Format: date-time */
            gymConsentConfirmedAt?: string | null;
            /** Format: int32 */
            maxExtensionDays: number;
            /** Format: int32 */
            qrCloseHoursAfterEnd: number;
            /** Format: int32 */
            qrOpenMinutesBefore: number;
        };
        ConfirmQrRequest: {
            token: string;
        };
        ConfirmQrResult: {
            alreadyConfirmed: boolean;
            attendance: components["schemas"]["AttendanceView"];
            markedAttended: boolean;
        };
        ConfirmResult: {
            alreadyConfirmed: boolean;
            attendance: components["schemas"]["AttendanceView"];
        };
        ConsentItemView: {
            /** Format: date-time */
            acceptedAt?: string | null;
            acceptedVersion?: string | null;
            active: boolean;
            applies: boolean;
            currentVersion: string;
            required: boolean;
            /** @enum {string} */
            type: "DATA_ADULT" | "DATA_GUARDIAN" | "WHATSAPP";
            upToDate: boolean;
        };
        ConsentTextView: {
            bodyMarkdown: string;
            draft: boolean;
            required: boolean;
            title: string;
            /** @enum {string} */
            type: "DATA_ADULT" | "DATA_GUARDIAN" | "WHATSAPP";
            version: string;
        };
        Cycle: {
            classes: components["schemas"]["ClassRow"][];
            cycle: components["schemas"]["CycleSummary"];
            otherEntries: components["schemas"]["ClassRow"][];
        };
        CycleOverview: {
            cycle?: components["schemas"]["CycleSummary"] | null;
            extension: components["schemas"]["ExtensionAvailability"];
            lastPayment?: components["schemas"]["PaymentSummary"] | null;
            payment: components["schemas"]["PaymentAvailability"];
            planName?: string | null;
        };
        CycleSummary: {
            /** Format: int32 */
            classesIncluded: number;
            /** Format: int32 */
            classesLost: number;
            /** Format: int32 */
            classesRemaining: number;
            /** Format: int32 */
            classesUsed: number;
            /** Format: date */
            endDate: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            /** Format: date */
            originalEndDate: string;
            /** Format: int32 */
            pendingMarks: number;
            /** Format: uuid */
            planId: string;
            /** Format: date */
            startDate: string;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "EXPIRED";
            /** Format: uuid */
            studentId: string;
        };
        EmergencyContactView: {
            name: string;
            phone: string;
            relationship: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EventCancelResult: {
            affectedStudents: components["schemas"]["AffectedStudent"][];
            event: components["schemas"]["EventView"];
        };
        EventView: {
            attendees: components["schemas"]["AttendeeView"][];
            canShowQr: boolean;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            endsAt: string;
            /** Format: int32 */
            freeSeats: number;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            /** Format: int32 */
            occupied: number;
            /** @enum {string} */
            phase: "PAST" | "NOW" | "UPCOMING";
            /** Format: date-time */
            startsAt: string;
            /** @enum {string} */
            status: "SCHEDULED" | "CANCELLED";
        };
        ExtendCycleCommand: {
            /** Format: date */
            newEndDate: string;
            reason: string;
        };
        ExtensionAvailability: {
            canExtendCycle: boolean;
            /** Format: date */
            extendFrom?: string | null;
            /** Format: date */
            extendUntil?: string | null;
        };
        GuardianInput: {
            /** Format: email */
            email?: string;
            name?: string;
            phone?: string;
            relationship?: string;
        };
        GuardianView: {
            email: string;
            name: string;
            phone: string;
            relationship: string;
        };
        Header: {
            /** Format: date */
            cycleEnd?: string | null;
            /** Format: date */
            cycleStart?: string | null;
            fullName: string;
            goal?: string | null;
            guardian?: components["schemas"]["GuardianView"] | null;
            /** Format: uuid */
            studentId: string;
            whatsappPhone?: string | null;
        };
        HistoryView: {
            activeCycle?: components["schemas"]["CycleSummary"] | null;
            cycles: components["schemas"]["Cycle"][];
        };
        InvitationAccepted: {
            email: string;
        };
        InvitationPreview: {
            accountEmail: string;
            /** @enum {string} */
            audience: "ADULT" | "GUARDIAN";
            brandName: string;
            consents: components["schemas"]["ConsentTextView"][];
            guardianName?: string | null;
            primaryColor?: string | null;
            studentName: string;
        };
        InviteResponse: {
            /** Format: date-time */
            expiresAt: string;
            inviteUrl: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MarkCommand: {
            /** @enum {string} */
            result: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH";
        };
        MarkEventCommand: {
            marks: components["schemas"]["MarkItem"][];
        };
        MarkItem: {
            /** Format: uuid */
            attendanceId: string;
            /** @enum {string} */
            status: "SCHEDULED" | "ATTENDED" | "CANCELLED_ON_TIME" | "RESCHEDULED" | "NO_SHOW" | "CANCELLED_BY_COACH";
        };
        MeResponse: {
            brandName: string;
            /** Format: uuid */
            coachId: string;
            /** Format: date-time */
            passwordChangedAt?: string | null;
            /** @enum {string|null} */
            passwordChangedBy?: "SELF" | "COACH_LINK" | null;
            primaryColor?: string | null;
            role: string;
            /** Format: uuid */
            userId: string;
        };
        PaymentAvailability: {
            /** @enum {string|null} */
            blockedBy?: "ACTIVE_CYCLE" | "PENDING_SESSIONS" | null;
            canRegisterPayment: boolean;
            /** Format: date */
            opensOn?: string | null;
            /** Format: date */
            paidOnMax?: string | null;
            /** Format: date */
            paidOnMin?: string | null;
        };
        PaymentRegistered: {
            /** Format: uuid */
            cycleId: string;
            /** Format: date */
            endDate: string;
            /** Format: uuid */
            paymentId: string;
            reference?: string | null;
            /** Format: date */
            startDate: string;
        };
        PaymentSummary: {
            /** Format: int64 */
            amountCop: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            cycleId: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            method: "NEQUI" | "TRANSFER" | "CASH" | "OTHER";
            /** Format: date */
            paidOn: string;
            /** Format: uuid */
            recordedBy: string;
            reference?: string | null;
            /** Format: uuid */
            studentId: string;
        };
        PlanInput: {
            /** Format: int32 */
            classesIncluded: number;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            name: string;
            /** Format: int64 */
            priceCop: number;
        };
        PlanSummary: {
            active: boolean;
            /** Format: int32 */
            classesIncluded: number;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            name: string;
            /** Format: int64 */
            priceCop: number;
        };
        QrView: {
            /** Format: date-time */
            availableFrom: string;
            /** Format: date-time */
            availableUntil: string;
            /** Format: date-time */
            expiresAt: string;
            token: string;
            url: string;
            /** Format: int64 */
            validForSeconds: number;
        };
        RegisterCoachRequest: {
            /** Format: email */
            email: string;
            name: string;
            password?: string;
        };
        RegisterPaymentCommand: {
            /** Format: int64 */
            amountCop: number;
            /** @enum {string} */
            method: "NEQUI" | "TRANSFER" | "CASH" | "OTHER";
            overrideModality?: boolean;
            overrideReason?: string;
            /** Format: date */
            paidOn?: string;
            /** Format: uuid */
            planId: string;
            reference?: string;
        };
        ResetLinkResponse: {
            /** Format: date-time */
            expiresAt: string;
            resetUrl: string;
        };
        ResetPasswordRequest: {
            newPassword?: string;
            token: string;
        };
        SheetView: {
            classes: components["schemas"]["ClassRow"][];
            cycle?: components["schemas"]["CycleSummary"] | null;
            header: components["schemas"]["Header"];
            otherEntries: components["schemas"]["ClassRow"][];
        };
        SlotView: {
            /** Format: date-time */
            endsAt: string;
            localDate: string;
            localTime: string;
            /** Format: date-time */
            startsAt: string;
        };
        StudentAccountView: {
            active: boolean;
            hasAccount: boolean;
            /** Format: date-time */
            openResetLinkUntil?: string | null;
            /** Format: date-time */
            passwordChangedAt?: string | null;
            /** @enum {string|null} */
            passwordChangedBy?: "SELF" | "COACH_LINK" | null;
        };
        StudentBillingOverview: {
            /** Format: int32 */
            classesRemaining?: number | null;
            /** Format: date */
            endDate?: string | null;
            fullName: string;
            /** Format: int32 */
            pendingMarks: number;
            /** @enum {string} */
            status: "ACTIVE" | "EXPIRING_SOON" | "NO_CYCLE";
            /** Format: uuid */
            studentId: string;
        };
        StudentBoard: {
            counts: components["schemas"]["BoardCounts"];
            students: components["schemas"]["BoardRow"][];
        };
        StudentCancelCommand: {
            /** Format: date-time */
            newStartsAt?: string;
        };
        StudentConsentsView: {
            anonymizationRequested: boolean;
            /** @enum {string|null} */
            audience?: "ADULT" | "GUARDIAN" | null;
            consents: components["schemas"]["ConsentItemView"][];
            /** Format: uuid */
            studentId: string;
        };
        StudentInput: {
            /** Format: date */
            birthDate: string;
            /** Format: email */
            email?: string;
            fullName: string;
            goal?: string;
            guardian?: components["schemas"]["GuardianInput"];
            whatsappPhone?: string;
        };
        StudentProfile: {
            account: components["schemas"]["StudentAccountView"];
            consents: components["schemas"]["StudentConsentsView"];
            cycle: components["schemas"]["CycleOverview"];
            emergencyContact?: components["schemas"]["EmergencyContactView"] | null;
            student: components["schemas"]["StudentSummary"];
            upcoming: components["schemas"]["UpcomingClass"][];
        };
        StudentSlotView: {
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            eventId?: string | null;
            localDate: string;
            localTime: string;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            /** Format: int32 */
            occupied: number;
            /** Format: date-time */
            startsAt: string;
        };
        StudentSummary: {
            active: boolean;
            /** @enum {string|null} */
            ageAlert?: "NONE" | "TURNS_ADULT_SOON" | "TURNED_ADULT_NEEDS_AUTHORIZATION" | null;
            anonymizationRequested: boolean;
            /** @enum {string|null} */
            audience?: "ADULT" | "GUARDIAN" | null;
            /** Format: date */
            birthDate?: string | null;
            /** Format: int64 */
            daysUntilAdult: number;
            email: string;
            fullName: string;
            goal?: string | null;
            guardian?: components["schemas"]["GuardianView"] | null;
            hasAccount: boolean;
            /** Format: uuid */
            id: string;
            minor: boolean;
            /** Format: date */
            turnsAdultOn?: string | null;
            whatsappPhone?: string | null;
        };
        StudentWithInvite: {
            /** Format: date-time */
            inviteExpiresAt: string;
            inviteUrl: string;
            student: components["schemas"]["StudentSummary"];
        };
        TodayView: {
            date: string;
            events: components["schemas"]["EventView"][];
        };
        TokenRequest: {
            token: string;
        };
        UpcomingClass: {
            /** Format: uuid */
            attendanceId: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            modality: "PERSONALIZED" | "SEMI_PERSONALIZED";
            /** Format: date-time */
            startsAt: string;
            today: boolean;
        };
        UpdateBrandRequest: {
            brandName: string;
            primaryColor: string;
        };
        UpdateCoachSettings: {
            /** Format: int32 */
            cancelWindowHours: number;
            /** Format: int32 */
            classDurationMinutes: number;
            /** Format: int32 */
            confirmationWindowHours: number;
            /** Format: int32 */
            defaultGroupCapacity: number;
            /** Format: int32 */
            expiringSoonClasses: number;
            /** Format: int32 */
            expiringSoonDays: number;
            gymConsentConfirmed: boolean;
            /** Format: int32 */
            maxExtensionDays: number;
            /** Format: int32 */
            qrCloseHoursAfterEnd: number;
            /** Format: int32 */
            qrOpenMinutesBefore: number;
        };
        UpdateStudentRequest: {
            active?: boolean;
            data: components["schemas"]["StudentInput"];
        };
        WindowInput: {
            /** Format: int32 */
            dayOfWeek: number;
            end: string;
            start: string;
        };
        WindowView: {
            /** Format: int32 */
            dayOfWeek: number;
            end: string;
            start: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    registerCoach: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCoachRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agenda: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgendaView"];
                };
            };
        };
    };
    pending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"][];
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntryView"][];
                };
            };
        };
    };
    cancelAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachCancelCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CancelResult"];
                };
            };
        };
    };
    mark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"];
                };
            };
        };
    };
    weekly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WindowView"][];
                };
            };
        };
    };
    replaceWeekly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WindowInput"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WindowView"][];
                };
            };
        };
    };
    blocks: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockSummary"][];
                };
            };
        };
    };
    createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BlockCreated"];
                };
            };
        };
    };
    deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentBillingOverview"][];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BrandView"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrandRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BrandView"];
                };
            };
        };
    };
    extend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendCycleCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CycleSummary"];
                };
            };
        };
    };
    cancelEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelEventCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventCancelResult"];
                };
            };
        };
    };
    changeCapacity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeCapacityCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventView"];
                };
            };
        };
    };
    markEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkEventCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"][];
                };
            };
        };
    };
    qr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QrView"];
                };
            };
        };
    };
    payments: {
        parameters: {
            query: {
                studentId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentSummary"][];
                };
            };
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanSummary"][];
                };
            };
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanSummary"];
                };
            };
        };
    };
    updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanSummary"];
                };
            };
        };
    };
    setPlanActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanSummary"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoachSettingsView"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCoachSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoachSettingsView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentWithInvite"];
                };
            };
        };
    };
    board: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentBoard"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSummary"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSummary"];
                };
            };
        };
    };
    coachView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentConsentsView"];
                };
            };
        };
    };
    coachAccept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                type: "DATA_ADULT" | "DATA_GUARDIAN" | "WHATSAPP";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptConsentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentConsentsView"];
                };
            };
        };
    };
    coachRevoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                type: "DATA_ADULT" | "DATA_GUARDIAN" | "WHATSAPP";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentConsentsView"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InviteResponse"];
                };
            };
        };
    };
    issueReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResetLinkResponse"];
                };
            };
        };
    };
    revokeReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentProfile"];
                };
            };
        };
    };
    sheet: {
        parameters: {
            query?: {
                cycleId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SheetView"];
                };
            };
        };
    };
    cancelAttendances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelAttendancesCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CancelAttendancesResult"];
                };
            };
        };
    };
    cycles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CycleSummary"][];
                };
            };
        };
    };
    activeCycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CycleSummary"];
                };
            };
        };
    };
    registerPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPaymentCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentRegistered"];
                };
            };
        };
    };
    attendancesOfStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"][];
                };
            };
        };
    };
    book_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachBookCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"];
                };
            };
        };
    };
    today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TodayView"];
                };
            };
        };
    };
    accept_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitationAccepted"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitationPreview"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    confirmQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmQrRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConfirmQrResult"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConfirmResult"];
                };
            };
        };
    };
    mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentConsentsView"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "DATA_ADULT" | "DATA_GUARDIAN" | "WHATSAPP";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptConsentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentConsentsView"];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "DATA_ADULT" | "DATA_GUARDIAN" | "WHATSAPP";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentConsentsView"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HistoryView"];
                };
            };
        };
    };
    mySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"][];
                };
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttendanceView"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StudentCancelCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CancelResult"];
                };
            };
        };
    };
    slots: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSlotView"][];
                };
            };
        };
    };
}
