// Writes the static-host header files from security-headers.mjs, for the API origin in API_ORIGIN.
//   API_ORIGIN=https://api.example.co node scripts/gen-headers.mjs           write public/_headers and vercel.json
//   node scripts/gen-headers.mjs --check                                      fail when they drifted (checks the committed API origin)
// Staging / production: regenerate with the real API origin (it is public information, not a secret) and commit.
import { readFileSync, writeFileSync } from 'node:fs';
import { CACHE_RULES, DEFAULT_API_ORIGIN, securityHeaders } from '../security-headers.mjs';

const check = process.argv.includes('--check');
const apiOrigin = process.env.API_ORIGIN ?? DEFAULT_API_ORIGIN;
const headers = securityHeaders({ apiOrigin });

const headersFile = [
  '# GENERATED by scripts/gen-headers.mjs from security-headers.mjs. Netlify / Cloudflare Pages format.',
  '/*',
  ...Object.entries(headers).map(([k, v]) => `  ${k}: ${v}`),
  ...CACHE_RULES.flatMap((r) => [r.source.replace('(.*)', '*'), `  Cache-Control: ${r.value}`]),
  '',
].join('\n');

const vercel = {
  $comment: 'GENERATED by scripts/gen-headers.mjs from security-headers.mjs. API origin: ' + apiOrigin,
  cleanUrls: false,
  headers: [
    { source: '/(.*)', headers: Object.entries(headers).map(([key, value]) => ({ key, value })) },
    ...CACHE_RULES.map((r) => ({ source: r.source, headers: [{ key: 'Cache-Control', value: r.value }] })),
  ],
  // client-side routes: the filesystem (assets, sw.js...) is served first, everything else is the single-page app
  rewrites: [{ source: '/(.*)', destination: '/index.html' }],
};
const vercelFile = JSON.stringify(vercel, null, 2) + '\n';

const files = [
  ['public/_headers', headersFile],
  ['vercel.json', vercelFile],
];
let drift = false;
for (const [path, content] of files) {
  if (check) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      /* missing */
    }
    if (current !== content) {
      console.error(`${path} does not match security-headers.mjs (API origin ${apiOrigin}): run "npm run gen:headers" and commit it.`);
      drift = true;
    }
  } else {
    writeFileSync(path, content);
    console.log(`Wrote ${path}`);
  }
}
if (check) {
  if (drift) process.exit(1);
  console.log('Static-host headers are up to date.');
}
