// Builds src/api/errorCatalog.generated.ts from ../docs/error-codes.md: the ONLY source of the error messages the person reads.
//   node scripts/gen-errors.mjs           write
//   node scripts/gen-errors.mjs --check   fail when the generated file does not match the document
import { readFileSync, writeFileSync } from 'node:fs';

const check = process.argv.includes('--check');
const target = 'src/api/errorCatalog.generated.ts';
const doc = readFileSync('../docs/error-codes.md', 'utf8');

const rows = [];
for (const line of doc.split('\n')) {
  const m = /^\|\s*`([A-Z][A-Z0-9_]+)`\s*\|\s*(\d{3})\s*\|\s*(.+?)\s*\|\s*$/.exec(line);
  if (m) rows.push({ code: m[1], status: Number(m[2]), message: m[3].replace(/\s+/g, ' ') });
}
if (rows.length === 0) throw new Error('no error rows found in docs/error-codes.md');
const seen = new Set();
for (const r of rows) {
  if (seen.has(r.code)) throw new Error(`code listed twice in docs/error-codes.md: ${r.code}`);
  seen.add(r.code);
}
rows.sort((a, b) => a.code.localeCompare(b.code));

const body = rows.map((r) => `  ${r.code}: { status: ${r.status}, message: ${JSON.stringify(r.message)} },`).join('\n');
const content = `// GENERATED by scripts/gen-errors.mjs from docs/error-codes.md. Do not edit: edit the document and run "npm run gen:errors".
export const ERRORS = {
${body}
} as const;

export type ErrorCode = keyof typeof ERRORS;
`;
if (check) {
  if (readFileSync(target, 'utf8') !== content) {
    console.error(`${target} does not match docs/error-codes.md: run "npm run gen:errors" and commit it.`);
    process.exit(1);
  }
  console.log(`Error catalog is up to date (${rows.length} codes).`);
} else {
  writeFileSync(target, content);
  console.log(`Wrote ${target} (${rows.length} codes).`);
}
